version: '3.8'

services:
    proxy:
      image: nginx
      ports:
      - 80:80
      build: .
      container_name: nginx10
      volumes:
        - type: bind
          source: ./mount
          target: /etc/nginx/
    frontend:
      image: frontend
      # ports:
      # - 5000:5000
      environment: 
        REACT_APP_BACKEND_URL: http://backend
      build: .
      container_name: frontend10
      
    backend:
      image: backend      
      # ports:
      # - 8080:8080
      environment:
        REDIS_HOST: redis10
        POSTGRES_HOST: postgres10
        REQUEST_ORIGIN: http://localhost        
      build: .
      container_name: backend10
      command: ["server"]     
    redis:
      image: redis
      build: .
      container_name: redis10
      restart: unless-stopped
    postgres:
      image: postgres
      build: .
      container_name: postgres10
      restart: unless-stopped
      volumes:
        - type: bind
          source: ./db
          target: /var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres      