version: '3.8'

services:
    web:
      image: devopsdockeruh/simple-web-service
      ports:
      - 8080:8080
      build: .
#      volumes:
#        - ${PWD}/text.log:/usr/src/app/text.log
      container_name: simpleweb2
      command: ["server"]