version: '3.8'

services:
    frontend:
      image: frontend
      ports:
      - 5000:5000
      build: .
      container_name: frontend4
    backend:
      image: backend
      ports:
      - 8080:8080
      environment:
        REDIS_HOST: redis2
        POSTGRES_HOST: postgres
      build: .
      container_name: backend4
      command: ["server"]     
    redis:
      image: redis
      build: .
      container_name: redis2
      restart: unless-stopped
    postgres:
      image: postgres
      build: .
      container_name: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres      